apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-cicd-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-cicd-app
  template:
    metadata:
      labels:
        app: spring-boot-cicd-app
    spec:
      containers:
        - name: spring-boot-cicd-app
          image: raghugrinindia/spring-boot-cicd-pipeline:1.0.0-19
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
