apiVersion: v1
kind: Service
metadata:
  name: spring-boot-cicd-pipeline-service
  labels:
    app: spring-boot-cicd-pipeline-app
spec:
  selector:
    app: spring-boot-cicd-pipeline-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
