apiVersion: v1
kind: Service
metadata:
  name: spring-boot-cicd-service
  labels:
    app: spring-boot-cicd-app
spec:
  selector:
    app: spring-boot-cicd-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
